### ISSUE TITLE
Problème redémarrage de l'Addon après redémarrage de HA

### ISSUE THREAD

**Issue by Yoyouri** [fmartinou/tydom2mqtt#169]
Bonjour,
Après avoir galéré a le faire fonctionné, je vois qu'à chaque fois que je redémarre Home Assistant, l'addon [tydom2mqtt] ne redémarre pas alors que le lancement au démarrage et le chien de garde est activer.
Je suis obligé de relancer l'appairage depuis ma box Tydon V1 et de démarrer manuellement l'addon
Y a t-il une solution pour régler se problème ?
Merci par avance

**Comment by JimmyTournemaine** [comment]
Hello, I'm facing the same issue.
When HA restarts, the add-on doesn't work until a manual restart is done.
Maybe it is starting before some requirements from HA are met.

I created a temporary automation to fix this until a fix is made.
```yaml
alias: "[Test] Fix Tydom"
description: Redémarre le module complémentaire Tydom, après redémarrage d’Home Assistant
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: hassio.addon_restart
    metadata: {}
    data:
      addon: 6b64d821_tydom2mqtt
mode: single
```
