### ISSUE TITLE
position transitoirement erronée pour les "cover"

### ISSUE THREAD

**Issue by musapinar** [fmartinou/tydom2mqtt#250]
J'ai une automatisation destinée à allumer la lumière après que les stores soient entièrement fermés :

```
alias: Close cover.cuisine_pano at sunset
description: Close the cuisine_pano rolling shutter a few minutes before sunset
triggers:
  - event: sunset
    offset: "-00:15:00"
    trigger: sun
conditions:
  - condition: state
    entity_id: cover.cuisine_pano
    state: open
actions:
  - target:
      entity_id: cover.cuisine_pano
    action: cover.close_cover
    data: {}
mode: single
```

```
alias: Turn on cuisine spots after cover.cuisine_pano has closed
triggers:
  - entity_id: cover.cuisine_pano
    to: closed
    trigger: state
conditions:
  - condition: state
    entity_id: light.televariateur_cuisine
    state: "off"
  - condition: sun
    before: sunset
    before_offset: "00:15:00"
actions:
  - entity_id: light.televariateur_cuisine
    action: light.turn_on
mode: single
```

J'ai observé l'anomalie suivante : Les spots s'allument au moment où le moteur entame la descente des volets. Or je souhaite les allumer après qu'ils aient terminé leur course.

Après investigation, j'explique ce dysfonctionnement par le constat suivant : Quand on demande à fermer le volet, que ce soit via la gui avec la card, ou via une automatisation avec `action: cover.close_cover`, alors, très brièvement, l'espace d'un instant, les attributes (notamment `position` et `current_position` et le `state`) sont valorisés avec les valeurs cibles. C'est-à-dire qu'on va avoir "state=closed, position=0, current_position=0" au moment où le moteur va initialiser la descente du volet, avant qu'il ne corrige immédiatement avec les "vraies" valeurs, c'est-à-dire position=100 qui va descrescendo jusqu'à zéro.

J'ai constaté la même anomalie à partir de n'importe quelle position initiale, ce n'est pas limité au mouvement "depuis entièrement ouvert vers entièrement fermé". Par exemple, si j'ai le volet à moitié ouvert (position=50), et que je le ferme, j'observe un bon de la valeur position à zéro, avant avant un rebond correct à 49, 48, 47, ..., 3, 2, 1, 0

Si cela peut aider à limiter le périmètre de recherche de ce que je crois être une régression : je n'avais pas ce problème avec la dernière version de fmartinou.

Merci.
