### ISSUE TITLE
External temperature entities lost

### ISSUE THREAD

**Issue by mitchbzh** [fmartinou/tydom2mqtt#254]
I change the hassio-addon from fmartinou to Tydom2mqqt to get the last version, but it broke something with the external temperature sensor.

Tydom2mqtt get well the event from the sensor:

`2025-03-09 21:35:22,107 - tydom.MessageHandler - INFO    - Device update (id=1666716344, endpoint=1666716344, name=Sonde Extérieure, type=conso)`
`2025-03-09 21:35:22,108 - sensors.Sensor       - INFO    - Sensor created / updated : outTemperature 10.79`

And I can retrieve the temperature values via its topic:

<img width="742" alt="Image" src="https://github.com/user-attachments/assets/d41acf30-5156-4349-aeae-fbeda72cfb4a" />

But HA doesn't see it anymore:

<img width="774" alt="Image" src="https://github.com/user-attachments/assets/3ac60da5-11ec-4e03-9672-1ea396125650" />

<img width="1502" alt="Image" src="https://github.com/user-attachments/assets/18f54e77-8899-409b-82b4-b1f9e7dade48" />

<img width="424" alt="Image" src="https://github.com/user-attachments/assets/1810397d-9647-4aa9-a9a6-96a90d9fc134" />

In my memory of a few months ago, an update of HA reject “C” for unit_of_measurement of a temperature, this is the unit in the file **MessageHandler.py** in dictionary **device_conso_unit_of_measurement{}** instead of "°C".  I think I changed it directly in the file, but I don't remember how, and the repo update broke my change.
I'd tried to override the unit with Customize, but it doesn't work:
```
sensor.outtemperature_tydom_produit_1:
  unit_of_measurement: "°C"
```

I've never managed to create an operational dev environment for debugging 😖, I therefore call on the experts to make this small correction 😊.
Note that all other devices works perfectly as before the update.

many thanks for your help

**Comment by mitchbzh** [comment]
home assitant core update 2025.3.2 solve the problem, it seems my assumption was wrong.
Sorry for the inconvenience, keep it up !

**Comment by mitchbzh** [comment]
The problem came again...
HA log:
`2025-07-08 20:20:45.914 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `C` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/tydom/outtemperature_tydom_1666716344_1666716344/config', message: '{'unique_id': 'outTemperature_tydom_1666716344_1666716344', 'device_class': 'temperature', 'unit_of_measurement': 'C', 'device': {'manufacturer': 'Delta Dore', 'identifiers': '1666716344_1666716344', 'model': 'Sensor', 'name': 'Sonde Extérieure'}, 'state_topic': 'sensor/tydom/outTemperature_tydom_1666716344_1666716344/state', 'name': 'outTemperature'}'`

Any help ?

**Comment by mitchbzh** [comment]
Workaround by creating a new MQTT probe, while waiting for the unit of measurement to be corrected as described in my 1st post.
In **configuration.yaml** file:
```
mqtt:
  sensor:
    - name: "Température extérieure"
      unique_id: "outTemperature_Tydom"
      state_topic: "sensor/tydom/outTemperature_tydom_1666716344_1666716344/state"
      icon: mdi:thermometer
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
      value_template: "{{value_json | float}}"
```
