### ISSUE TITLE
2 Tydom connections

### ISSUE THREAD

**Issue by gadame74** [fmartinou/tydom2mqtt#29]
Hello.

I am very grateful for this addon, it's running perfectly.

But some installations have more than 1 Tydom Hub. therefore they have 2 (or more)  mac address, and tydom password.

How could I connect more than 1 Tydom hub? Could I install the same repository twice? (I don't know do it) or, could I  add on the yaml file more:

TYDOM_MAC:
TYDOM_IP:
TYDOM_PASSWORD:

Thanks for your ideas.
Gada

**Comment by fmartinou** [comment]
Hi,

To my knowledge, there is not possibility to run multiple instances of the same addon.

If you have control over the Docker engine of our machine, you can also run the container by yourself (as many instances as you wish).

Trivial example with docker-compose:
```yaml
version: '3'

services:
  tydom2mqtt_1:
    image: fmartinou/tydom2mqtt
    environment:
      - TYDOM_MAC=001A25XXXXXX
      - TYDOM_PASSWORD=azerty123456789
      - TYDOM_IP=192.168.1.33
      - MQTT_HOST=mosquitto
  tydom2mqtt_2:
    image: fmartinou/tydom2mqtt
    environment:
      - TYDOM_MAC=002B26XXXXXX
      - TYDOM_PASSWORD=azerty987654321
      - TYDOM_IP=192.168.1.34
      - MQTT_HOST=mosquitto
```
