### ISSUE TITLE
tydom2mqtt 2.4.0 Cover status not saved after ha reboot

### ISSUE THREAD

**Issue by cob94440** [fmartinou/tydom2mqtt#40]
Hello since 2.4.0 each time i have to reload or reboot HA, i need to close open my cover because their state is not good.
Some says that they are closed even if they're open, some says they're at 60% open even if all are open.The log seems to tell they're all open.maybe it doesn't update well mqtt.

**Comment by jerry34ha** [comment]
Same issue here: cover state is good only if I control them for HA. If I open them from the physical switch, state is not updated. HA restart, HA reboot, MQTT restart, mqtt2addon restart: none of this fixes the problem.

**Comment by mopi1402** [comment]
Hello,
I think we should probably listen to event from the websocket of Tydom in order to update the values on MQTT... So they may be replicate on Home Assistant.

**Comment by jrlacharnay** [comment]
On my side a restart of tydom2mqtt fixes the problem.

So I added the following automation:

![image](https://user-images.githubusercontent.com/20613054/206812987-cdb5a696-7e4d-44aa-8f06-74faaa3634e4.png)

```yaml
alias: Restart tydom2mqtt on HA startup
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: hassio.addon_restart
    data:
      addon: 6b64d821_tydom2mqtt
mode: single
```
