### ISSUE TITLE
Bad step resolution in HA

### ISSUE THREAD

**Issue by Bobdugrand8** [fmartinou/tydom2mqtt#59]
For boiler (actually Heat pump) the step resolution is 1°C in HA but in fact in tydom app it is 0.5 °C.
If it's set with tydom app it's stay to 0.5°C and can be seen in HA with the good value.

I didn't find where it's set in the app? I'm missing something?

**Comment by olliewills** [comment]
I know this is an older issue but I have the same issue even today and it would super great to see it resolved. I can set the temperature in 0.5 degree increments with automations of course, but sometimes I want to bump the heating up/down a bit using the card interface and with that I'm limited to 1 degree increments.

**Comment by olliewills** [comment]
In case anyone is interested, I found a workaround for this issue. You can add the following code to your configuration.yaml and it will override the default 1 degree step value of the addon to make it 0.5 like the physical thermostat. `climate.mqtt_XXX` is the entity name of the thermostat exposed by the addon. 

```
homeassistant:
  customize:
    climate.mqtt_1734557249_1734557249:
      target_temp_step: 0.5
    climate.mqtt_1734557174_1734557174:
      target_temp_step: 0.5
```
