### ISSUE TITLE
v2.6.6 : MQTT connection Error

### ISSUE THREAD

**Issue by Talw3g** [fmartinou/tydom2mqtt#64]
En utilisant la dernière version du container dans docker-compose, j'obtiens l'erreur suivante : 

> MQTT connection Error : 'str' object has no attribute 'wrap_bio'

Voici la config de mon docker-compose : 

```
  tydom2mqtt:
    image: fmartinou/tydom2mqtt:latest
    container_name: tydom2mqtt
    restart: unless-stopped
    environment:
      - TYDOM_MAC=00:00:00:00:00:00
      - TYDOM_PASSWORD=XXXXXXXX
      - TYDOM_IP=10.0.0.66
      - MQTT_HOST=mosquitto
      - MQTT_SSL=0
```
"mosquitto" est le nom du service docker-compose dans lequel tourne le broker mosquitto.
Un `ping mosquitto` ou `ping 10.0.0.66` renvoi bien une reponse.
